defaults:
  - scope:
      path: "README.md"
    values:
      permalink: ""
      lang: "en"
      title: "Sustainable"
      description: "Experience the world sustainably."
  - scope:
      path: "de/README.md"
    values:
      permalink: "de"
      lang: "de"
      title: "Nachhaltig"
      description: "Erlebe die Welt nachhaltig."
